      <!-- main area -->
      <div class="main-content">
        <div class="page-title">
          <div class="title">Add new consignment</div>
          <div class="sub-title">
        <?php if(isset($addClientMsg)){ ?>
          <div class="card-header"> 
              <strong style="color: red; font-size: 16px;"><?php echo $addClientMsg['addClientMsg']; ?></strong>
          </div>
          <?php }?>
        </div>
        <div class="card-block">
        	<?php echo form_open_multipart('cs/addConsigment','role="form"');?>
        		<div class="form-group">
        			<label class="form-control">
        				<li>Kindly note that <strong><i>UNIQUE FILE NUMBER</i></strong> and <strong><i>DATE INVOICED</i></strong> will be automatically generated by the system</li>
        			</label><br><hr>
        		</div>
        		<div class="form-group">
        			<label class="control-label col-sm-1">Basic details: </label>
        			<div class="col-sm-10">
	        			<select name="cons_cargo_type" class="cust-col col-sm-3" required="" title="Select Cargo type as either Loose or Full container cargo">
	        				<option selected="" disabled="">Select cargo type</option>
	        				<option value="Loose">Loose cargo</option>
	        				<option value="Full container">Full container cargo</option>
	        			</select>
	        			<select class="cust-col col-sm-2" name="cons_urgency" required="" title="Select Urgency. It can be urgent or normal">
	        				<option selected="" disabled="">Urgency</option>
	        				<option value="Urgent">Urgent</option>
	        				<option value="Normal">Normal</option>
	        			</select>
	        			<select name="cons_regime" class="cust-col col-sm-2" title="Select the regime. It can be Home use, etc." required="">
	        				<option selected="" disabled="">Regime</option>
	        				<option value="Home use">Home use</option>
	        			</select>
	        			<select class="cust-col col-sm-2" name="cons_import_export" title="Is it an Import or Export?" required="">
	        				<option selected="" disabled="">Import or Export</option>
	        				<option value="Import">Import</option>
	        				<option value="Export">Export</option>
	        				<option value="Local">Local</option>
	        			</select>
	        			<select class="cust-col col-sm-3" name="cons_trans_type" title="Mode of transport. Is it by Air, Sea or Road?" required="">
	        				<option selected="" disabled="">by Air, Sea or Road</option>
	        				<option value="Airfreight">Airfreight</option>
	        				<option value="Seafreight">Seafreight</option>
	        				<option value="Road">By Road</option>
	        			</select>
        			</div>
        		</div><br><br>
        		<div class="form-group">
        			<label class="control-label col-sm-1">Entry no.</label>
        			<div class="col-sm-10">
        				<input type="text" name="cons_entry_number" class="form-control cust-col" required="" placeholder="Entry number" title="Entry number">
        			</div>
        		</div><br><br>
        		<div class="form-group">
        			<label class="control-label col-sm-1">Date opened</label>
        			<div class="col-sm-10">
        				<input type="date" name="cons_date_opened" class="form-control cust-col" required="" placeholder="Date opened" title="Date opened">
        			</div>
        		</div><br><br>
        		<div class="form-group">
        			<label class="control-label col-sm-1">Parties</label>
        			<div class="col-sm-10">
        				<input type="text" name="cust_id" class="cust-col col-sm-4" required="" placeholder="Client" title="Client" list="clients">
        				<input type="text" name="cons_shipper" class="cust-col col-sm-4" required="" placeholder="Shipper" title="Shipper" list="shipper">
        				<input type="text" name="cons_consignee" class="cust-col col-sm-4" required="" placeholder="Consignee" title="Consignee">
        			</div>
        		</div><br><br>
        		<div class="form-group">
        			<label class="control-label col-sm-1">Consignment Description</label>
        			<div class="col-sm-10">
        				<input type="text" name="cons_desc" class="form-control cust-col" required="" title="Write description of the consignment here" placeholder="Consignment Description">
        			</div>
        		</div><br><br>
        		<div class="form-group">
        			<label class="control-label col-sm-1">HAWB No.</label>
        			<div class="col-sm-10">
        				<input type="number" name="hawb_no" class="cust-col col-sm-4" placeholder="HAWB No." title="HAWB No.">
        				<input type="number" name="hawb_charge" class="cust-col col-sm-4" placeholder="HAWB Charge amount" title="HAWB Charge amount">
        				<input type="file" name="hawb_image" class="cust-col col-sm-4" placeholder="HAWB Scanned image" title="HAWB Scanned image">
        			</div>
        		</div><br><br>
        		<div class="form-group">
        			<label class="control-label col-sm-1">MAWB No.</label>
        			<div class="col-sm-10">
        				<input type="number" name="mawb" class="cust-col col-sm-4" required="" placeholder="MAWB No." title="MAWB No.">
        				<input type="number" name="mawb_charge" class="cust-col col-sm-4" placeholder="MAWB Charge amount" title="MAWB Charge amount">
        				<input type="file" name="Mawb_image" class="cust-col col-sm-4" placeholder="MAWB Scanned image" title="MAWB Scanned image">
        			</div>
        		</div><br><br>
        		<div class="form-group">
        			<label class="control-label col-sm-1">Freight/Vessel No</label>
        			<div class="col-sm-10">
        				<input type="text" name="cons_freight_vessel_no" class="form-control cust-col" required="" placeholder="Freight/Vessel No" title="Freight/Vessel No">
        			</div>
        		</div><br><br>
        		<div class="form-group">
        			<label class="control-label col-sm-1">Measurement (Weight,Pkgs)</label>
        			<div class="col-sm-10">
        				<input type="text" name="cons_weight" class="cust-col col-sm-6" required="" placeholder="Weight" title="Weight">
        				<input type="text" name="cons_pkgs" class="cust-col col-sm-6" required="" placeholder="No of Pkgs" title="No of Pkgs">
        			</div>
        		</div><br><br>
        		<div class="form-group">
        			<label class="control-label col-sm-1">Dimensions (L,W,H)</label>
        			<div class="col-sm-10">
        				<input type="text" name="cons_length" class="cust-col col-sm-4" required="" placeholder="Length" title="Length">
        				<input type="text" name="cons_width" class="cust-col col-sm-4" required="" placeholder="Width" title="Width">
        				<input type="text" name="cons_height" class="cust-col col-sm-4" required="" placeholder="Height" title="Height">
        			</div>
        		</div><br><br>
        		<div class="form-group">
        			<label class="control-label col-sm-1">Comm Invoice No</label>
        			<div class="col-sm-10">
        				<input type="text" name="comm_inv" class="cust-col form-control" required="" placeholder="Commercial invoice number" title="Coomercial invoice number">
        			</div>
        		</div><br><br>
        		<div class="form-group">
        			<label class="control-label col-sm-1">ETD,ETA</label>
        			<div class="col-sm-10">
        				<input type="date" name="cons_etd" class="cust-col col-sm-6" required="" placeholder="ETD" title="ETD">
        				<input type="date" name="cons_eta" class="cust-col col-sm-6" required="" placeholder="ETA" title="ETA">
        			</div>
        		</div><br><br>
                <div class="form-group">
                    <button class="btn btn-primary">ADD CONSIGNMENT</button>
                </div>
        	<?php echo form_close();?>
        </div>
      </div>
      <!-- /main area -->
    </div>
    <!-- /content panel -->
    <!-- bottom footer -->
    <!-- Modal -->
<div id="newCompany" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content col-sm-12">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Add new company</h4>
      </div>
      <div class="modal-body">
      <form role="form" method="post" action="<?php echo base_url('sales/addClient');?>" >
        <div class="form-group">
          <input type="text" name="cname" class="form-control" placeholder="Company name">
        </div>
        <div class="form-group">
          <input type="text" name="cemail" class="form-control" placeholder="Company email">
        </div>
        <div class="form-group">
          <input type="text" name="cphone" class="form-control" placeholder="Company Telephone no.">
        </div>
        <div class="form-group">
          <button class="btn btn-primary">Finish</button>
        </div>
      </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>
<!--CLIENT LIST-->
<datalist id="clients">
    <?php foreach ($clients as $clients):?>
        <option value="<?php echo $clients->cust_id;?>"><?php echo $clients->client_name;?></option>
    <?php endforeach;?>
</datalist>
<datalist id="shipper">
    <option value="Avmax">Avmax</option>
</datalist>
<!--CSS-->
<style type="text/css">
  .cust-col{
    border-right: none; 
    border-top: none;
    border-left: none; 
    border-bottom-color: #b3b3ff; 
  }
</style>

