      <!-- main area -->
      <div class="main-content">
        <div class="page-title">
          <div class="title ifcons">FILE NUMBER #</div>
        <div class="ifcons">
        	<?php echo form_open_multipart('ops/manageClient','role="form"');?>
        		<!-- <div class="form-group">
        			<label class="form-control">
        				<li>Kindly note that <strong><i>FILE NUMBER</i></strong> and <strong><i>DATE ADDED</i></strong> will be automatically generated by the system</li>
        			</label><br><hr>
        		</div> -->
        		<div class="form-group">
        			<div class="col-sm-2">
                <span class="input input--focused m-b-md">
                  <?php echo form_input('cons_cargo_type',$consData[0]->cons_cargo_type.' cargo','class="cust-col form-control input__field"');?>
                  <label class="input__label" for="input-2">
                    <span class="input__label-content">Cargo type</span>
                  </label>
                </span>
              </div>
              <div class="col-sm-2">
                <span class="input input--focused m-b-md">
                  <?php echo form_input('cons_urgency',$consData[0]->cons_urgency,'class="cust-col form-control input__field"');?>
                  <label class="input__label" for="input-2">
                    <span class="input__label-content">Consignment urgency</span>
                  </label>
                </span>	        			
              </div>
              <div class="col-sm-2">
                <span class="input input--focused m-b-md">
                  <?php echo form_input('cons_regime',$consData[0]->cons_regime,'class="cust-col form-control input__field"');?>
                  <label class="input__label" for="input-2">
                    <span class="input__label-content">Consignment regime</span>
                  </label>
                </span>	
              </div>
              <div class="col-sm-2">
                <span class="input input--focused m-b-md">
                  <?php echo form_input('cons_import_export',$consData[0]->cons_import_export,'class="cust-col form-control input__field"');?>
                  <label class="input__label" for="input-2">
                    <span class="input__label-content">Is import or export?</span>
                  </label>
                </span>	        			
              </div>
              <div class="col-sm-2">
                <span class="input input--focused m-b-md">
                  <?php echo form_input('cons_trans_type',$consData[0]->cons_trans_type,'class="cust-col form-control input__field"');?>
                  <label class="input__label" for="input-2">
                    <span class="input__label-content">Mode of transport</span>
                  </label>
                </span>
              </div>
        		</div><br><br>
        		<div class="form-group">
        			<div class="col-sm-10">
                <span class="input input--focused m-b-md">
                  <?php echo form_input('cons_entry_number',$consData[0]->cons_entry_number,'class="cust-col form-control input__field"');?>
                  <label class="input__label" for="input-2">
                    <span class="input__label-content">Entry number</span>
                  </label>
                </span>
        			</div>
        		</div><br><br>
        		<div class="form-group">
        			<div class="col-sm-10">
                <span class="input input--focused m-b-md">
                  <?php echo form_input('cons_date_opened',$consData[0]->cons_date_opened,'class="cust-col form-control input__field"');?>
                  <label class="input__label" for="input-2">
                    <span class="input__label-content">Date opened</span>
                  </label>
                </span>
        			</div>
        		</div><br><br>
        		<div class="form-group">
        			<div class="col-sm-3">
                <span class="input input--focused m-b-md">
                  <?php echo form_input('cust_id',$consData[0]->cust_id,'class="cust-col form-control input__field"');?>
                  <label class="input__label" for="input-2">
                    <span class="input__label-content">Client #</span>
                  </label>
                </span>
              </div>
              <div class="col-sm-3">
                <span class="input input--focused m-b-md">
                  <?php echo form_input('cons_shipper',$consData[0]->cons_shipper,'class="cust-col form-control input__field"');?>
                  <label class="input__label" for="input-2">
                    <span class="input__label-content">Shipper</span>
                  </label>
                </span>
              </div>
              <div class="col-sm-4">
                <span class="input input--focused m-b-md">
                  <?php echo form_input('cons_consignee',$consData[0]->cons_consignee,'class="cust-col form-control input__field"');?>
                  <label class="input__label" for="input-2">
                    <span class="input__label-content">Consignee</span>
                  </label>
                </span>
        			</div>
        		</div><br><br>
        		<div class="form-group">
        			<div class="col-sm-10">
                <span class="input input--focused m-b-md">
                  <?php echo form_input('cons_desc',$consData[0]->cons_desc,'class="cust-col form-control input__field"');?>
                  <label class="input__label" for="input-2">
                    <span class="input__label-content">Consignment Description</span>
                  </label>
                </span>
        			</div>
        		</div><br><br>
        		<div class="form-group">
        			<div class="col-sm-5">
                <span class="input input--focused m-b-md">
                  <?php echo form_input('cons_airline',$consData[0]->cons_airline,'class="cust-col form-control input__field"');?>
                  <label class="input__label" for="input-2">
                    <span class="input__label-content">Airline name</span>
                  </label>
                </span>
        			</div>
              <div class="col-sm-5">
                <span class="input input--focused m-b-md">
                  <?php echo form_input('cons_flight_no',$consData[0]->cons_flight_no,'class="cust-col form-control input__field"');?>
                  <label class="input__label" for="input-2">
                    <span class="input__label-content">Flight no</span>
                  </label>
                </span>
              </div>
        		</div><br><br>
        		<div class="form-group">
        			<div class="col-sm-5">
                <span class="input input--focused m-b-md">
                  <?php echo form_input('cons_weight',$consData[0]->cons_weight,'class="cust-col form-control input__field"');?>
                  <label class="input__label" for="input-2">
                    <span class="input__label-content">Weight in Kgs</span>
                  </label>
                </span>
        			</div>
              <div class="col-sm-5">
                <span class="input input--focused m-b-md">
                  <?php echo form_input('cons_pkgs',$consData[0]->cons_no_of_packages,'class="cust-col form-control input__field"');?>
                  <label class="input__label" for="input-2">
                    <span class="input__label-content">No of packages</span>
                  </label>
                </span>
              </div>
        		</div><br><br>
        		<div class="form-group">
        			<div class="col-sm-3">
                <span class="input input--focused m-b-md">
                  <?php echo form_input('cons_length',$consData[0]->cons_length,'class="cust-col form-control input__field"');?>
                  <label class="input__label" for="input-2">
                    <span class="input__label-content">Length in Mtrs</span>
                  </label>
                </span>
        			</div>
              <div class="col-sm-3">
                <span class="input input--focused m-b-md">
                  <?php echo form_input('cons_width',$consData[0]->cons_width,'class="cust-col form-control input__field"');?>
                  <label class="input__label" for="input-2">
                    <span class="input__label-content">Width in Mtrs</span>
                  </label>
                </span>
              </div>
              <div class="col-sm-4">
                <span class="input input--focused m-b-md">
                  <?php echo form_input('cons_height',$consData[0]->cons_height,'class="cust-col form-control input__field"');?>
                  <label class="input__label" for="input-2">
                    <span class="input__label-content">Height in Mtrs</span>
                  </label>
                </span>
              </div>
        		</div><br><br>
        		<div class="form-group">
        			<div class="col-sm-3">
                <span class="input input--focused m-b-md">
                  <?php echo form_input('comm_inv',$consData[0]->cons_comm_inv_no,'class="cust-col form-control input__field"');?>
                  <label class="input__label" for="input-2">
                    <span class="input__label-content">Commercial invoice number</span>
                  </label>
                </span>
        			</div>
              <div class="col-sm-3">
                <span class="input input--focused m-b-md">
                  <?php echo form_input('comm_inv_date',$consData[0]->cons_comm_inv_date,'class="cust-col form-control input__field"');?>
                  <label class="input__label" for="input-2">
                    <span class="input__label-content">Commercial invoice date</span>
                  </label>
                </span>
              </div>
              <div class="col-sm-4">
                <span class="input input--focused m-b-md">
                  <?php echo form_input('comm_inv_value',$consData[0]->cons_comm_inv_value,'class="cust-col form-control input__field"');?>
                  <label class="input__label" for="input-2">
                    <span class="input__label-content">Commercial invoice value</span>
                  </label>
                </span>
              </div>
        		</div><br><br>
        		<div class="form-group">        			
              <div class="col-sm-5">
                <span class="input input--focused m-b-md">
                  <?php echo form_input('cons_etd',$consData[0]->cons_etd,'class="cust-col form-control input__field"');?>
                  <label class="input__label" for="input-2">
                    <span class="input__label-content">Consignment ETD</span>
                  </label>
                </span>
              </div>
              <div class="col-sm-5">
                <span class="input input--focused m-b-md">
                  <?php echo form_input('cons_eta',$consData[0]->cons_eta,'class="cust-col form-control input__field"');?>
                  <label class="input__label" for="input-2">
                    <span class="input__label-content">Consignment ETA</span>
                  </label>
                </span>
              </div>
        		</div><br><br>
            <div class="form-group">              
              <div class="col-sm-5">
                <span class="input input--focused m-b-md">
                  <?php echo form_input('cons_origin_country',$consData[0]->cons_country_of_origin ,'class="cust-col form-control input__field"');?>
                  <label class="input__label" for="input-2">
                    <span class="input__label-content">Country Origin</span>
                  </label>
                </span>
              </div>
              <div class="col-sm-5">
                <span class="input input--focused m-b-md">
                  <?php echo form_input('cons_destination_country',$consData[0]->cons_country_of_destination,'class="cust-col form-control input__field"','list="country"');?>
                  <label class="input__label" for="input-2">
                    <span class="input__label-content">Country destination</span>
                  </label>
                </span>
              </div>
            </div><br><br>
            <div class="form-group">              
              <div class="col-sm-5">
                <span class="input input--focused m-b-md">
                  <?php echo form_input('cons_origin_door',$consData[0]->cons_door_of_origin ,'class="cust-col form-control input__field"','list="country"');?>
                  <label class="input__label" for="input-2">
                    <span class="input__label-content">Origin port</span>
                  </label>
                </span>
              </div>
              <div class="col-sm-5">
                <span class="input input--focused m-b-md">
                  <?php echo form_input('cons_destination_door',$consData[0]->cons_door_of_delivery,'class="cust-col form-control input__field"','list="country"');?>
                  <label class="input__label" for="input-2">
                    <span class="input__label-content">Destination port</span>
                  </label>
                </span>
              </div>
            </div><br><br>
            <div class="form-group">              
              <div class="col-sm-10">
                <span class="input input--focused m-b-md">
                  <?php echo form_input('cons_category',$consData[0]->cons_category,'class="cust-col form-control input__field"','list="country"');?>
                  <label class="input__label" for="input-2">
                    <span class="input__label-content">Consignment category</span>
                  </label>
                </span>
              </div>
            </div><br><br>
            <div class="form-group">
              <div class="col-sm-10">
                <!-- <button class="btn btn-primary" style="width:100%;">ADD CONSIGNMENT</button> -->
              </div>
            </div><br><br><br><br><br><br><br><br><br>
          </div>
        	<?php echo form_close();?>
        </div>
      </div>
      <!-- /main area -->
    </div>
    <!-- /content panel -->
    <!-- bottom footer -->
    <!-- Modal -->
<div id="newCompany" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content col-sm-12">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Add new company</h4>
      </div>
      <div class="modal-body">
      <form role="form" method="post" action="<?php echo base_url('sales/addClient');?>" >
        <div class="form-group">
          <input type="text" name="cname" class="form-control" placeholder="Company name">
        </div>
        <div class="form-group">
          <input type="text" name="cemail" class="form-control" placeholder="Company email">
        </div>
        <div class="form-group">
          <input type="text" name="cphone" class="form-control" placeholder="Company Telephone no.">
        </div>
        <div class="form-group">
          <button class="btn btn-primary">Finish</button>
        </div>
      </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>
<!--CLIENT LIST-->
<datalist id="clients">
    <?php foreach ($clients as $clients):?>
        <option value="<?php echo $clients->cust_id;?>"><?php echo $clients->client_name;?></option>
    <?php endforeach;?>
</datalist>
<datalist id="shipper">
    <option value="Avmax">Avmax</option>
</datalist>
<!--CSS-->
<style type="text/css">
  .cust-col{
    border-right: none; 
    border-top: none;
    border-left: none; 
    border-bottom-color: #b3b3ff; 
  }
  .c30{
    width: 100%;
  }
</style>
<script type="text/javascript">
  jQuery(function($){
  $('.table').footable({
    "showToggle": true
  });
});
