      <!-- main area -->
      <div class="main-content">
        <div class="page-title">
          <div class="title ifcons">Add new consignment</div>
          <div class="sub-title">
        <?php if(isset($cons_id)):?>
          <div class="card-header notcons"> 
            <div class="alert alert-dismissible alert-success">
              <button type="button" class="close" data-dismiss="alert" style="color: black;">&times;</button>
              <p style="font-size: 20px;"><strong>Well done!</strong> You successfully added consignment with unique id#<?php echo $cons_id; ?></p><hr>
              <?php echo form_open('cs/trackConsignment');?>
              <input type="text" name="track_cons_id" value="<?php echo $cons_id;?>" hidden="">
              <button class="btn btn-success">ADD MORE INFO</button>
              <?php echo form_close();?>
              <!-- PROGRESS BAR -->
                <div class="progress progress-striped active" style="min-height: 50px;">
                  <div class="progress-bar" style="width: <?php echo $cons_id;?>%;"></div>
                </div>
            <!-- //PROGRESS BAR -->
              <style type="text/css">
                  .ifcons{
                    display: none;
                  }
              </style>
            </div>
          </div>
        <?php else:?>
            <style type="text/css">
                .notcons{
                    display: none;
                }
            </style>
        <?php endif;?>

        </div>
        <div class="ifcons">
        	<?php echo form_open_multipart('cs/addConsigment','role="form"');?>
        		<div class="form-group">
        			<label class="form-control">
        				<li>Kindly note that <strong><i>UNIQUE FILE NUMBER</i></strong> and <strong><i>DATE ADDED</i></strong> will be automatically generated by the system</li>
        			</label><br><hr>
        		</div>
        		<div class="form-group">
        			<div class="col-sm-2">
                <span class="input input--focused m-b-md">                  
                  <select name="cons_cargo_type" class="cust-col form-control input__field" required="" style="width: 100%;">
                    <option selected="" disabled="">Select cargo type here</option>
                    <option value="Loose">Loose cargo</option>
                    <option value="Full container">Full container cargo</option>
                  </select>
                  <label class="input__label" for="input-2">
                    <span class="input__label-content">Cargo type</span>
                  </label>
                </span>
              </div>
              <div class="col-sm-2">
                <span class="input input--focused m-b-md">
                  <select class="cust-col form-control input__field" name="cons_urgency" required="" style="width: 100%;">
                  <option selected="" disabled="">Select urgency here</option>
                  <option value="Urgent">Urgent</option>
                  <option value="Normal">Normal</option>
                  <option value="AOG">AOG</option>
                  </select>
                  <label class="input__label" for="input-2">
                    <span class="input__label-content">Consignment urgency</span>
                  </label>
                </span>	        			
              </div>
              <div class="col-sm-2">
                <span class="input input--focused m-b-md">
                  <select name="cons_regime" class="cust-col form-control input__field" required="" style="width: 100%;">
                  <option selected="" disabled="">Select regime</option>
                  <option value="Home use">Home use</option>
                  </select>
                  <label class="input__label" for="input-2">
                    <span class="input__label-content">Consignment regime</span>
                  </label>
                </span>	
              </div>
              <div class="col-sm-2">
                <span class="input input--focused m-b-md">
                  <select class="cust-col form-control input__field" name="cons_import_export" required="" style="width: 100%;">
                  <option selected="" disabled="">Select if is import or export</option>
                  <option value="Import">Import</option>
                  <option value="Export">Export</option>
                  <option value="Local">Local</option>
                  </select>
                  <label class="input__label" for="input-2">
                    <span class="input__label-content">Is import or export?</span>
                  </label>
                </span>	        			
              </div>
              <div class="col-sm-2">
                <span class="input input--focused m-b-md">
                  <select class="cust-col form-control input__field" name="cons_trans_type" required="" style="width: 100%;">
                  <option selected="" disabled="">Select transport mode</option>
                  <option value="Airfreight">Airfreight</option>
                  <option value="Seafreight">Seafreight</option>
                  <option value="Road">By Road</option>
                  </select>
                  <label class="input__label" for="input-2">
                    <span class="input__label-content">Mode of transport</span>
                  </label>
                </span>
              </div>
        		</div><br><br>
        		<div class="form-group">
        			<div class="col-sm-10">
                <span class="input input--focused m-b-md">
                  <input class="input__field cust-col" type="number" name="cons_entry_number" placeholder="Enter entry number here" required="">
                  <label class="input__label" for="input-2">
                    <span class="input__label-content">Entry number</span>
                  </label>
                </span>
        			</div>
        		</div><br><br>
        		<div class="form-group">
        			<div class="col-sm-10">
                <span class="input input--focused m-b-md">
                  <input class="input__field cust-col" type="text" name="cons_date_opened" placeholder="Enter consignment opening date" required="" data-provide="datepicker">
                  <label class="input__label" for="input-2">
                    <span class="input__label-content">Date opened</span>
                  </label>
                </span>
        			</div>
        		</div><br><br>
        		<div class="form-group">
        			<div class="col-sm-3">
                <span class="input input--focused m-b-md">
                  <input class="input__field cust-col" type="text" name="cust_id" placeholder="Enter client# here" required="" list="clients">
                  <label class="input__label" for="input-2">
                    <span class="input__label-content">Client #</span>
                  </label>
                </span>
              </div>
              <div class="col-sm-3">
                <span class="input input--focused m-b-md">
                  <input class="input__field cust-col" type="text" name="cons_shipper" placeholder="Enter Shipper here" required="" list="shipper">
                  <label class="input__label" for="input-2">
                    <span class="input__label-content">Shipper</span>
                  </label>
                </span>
              </div>
              <div class="col-sm-4">
                <span class="input input--focused m-b-md">
                  <input class="input__field cust-col" type="text" name="cons_consignee" placeholder="Enter Consignee here" required="">
                  <label class="input__label" for="input-2">
                    <span class="input__label-content">Consignee</span>
                  </label>
                </span>
        			</div>
        		</div><br><br>
        		<div class="form-group">
        			<div class="col-sm-10">
                <span class="input input--focused m-b-md">
                  <input class="input__field cust-col" type="text" name="cons_desc" placeholder="Write description of the consignment here" required="">
                  <label class="input__label" for="input-2">
                    <span class="input__label-content">Consignment Description</span>
                  </label>
                </span>
        			</div>
        		</div><br><br>
        		<div class="form-group">
        			<div class="col-sm-5">
                <span class="input input--focused m-b-md">
                  <input class="input__field cust-col" type="text" name="cons_airline" placeholder="Airline name" required="">
                  <label class="input__label" for="input-2">
                    <span class="input__label-content">Airline name</span>
                  </label>
                </span>
        			</div>
              <div class="col-sm-5">
                <span class="input input--focused m-b-md">
                  <input class="input__field cust-col" type="number" name="cons_flight_no" placeholder="Flight no." required="">
                  <label class="input__label" for="input-2">
                    <span class="input__label-content">Flight no</span>
                  </label>
                </span>
              </div>
        		</div><br><br>
        		<div class="form-group">
        			<div class="col-sm-5">
                <span class="input input--focused m-b-md">
                  <input class="input__field cust-col" type="number" name="cons_weight" placeholder="Enter Weight in Kgs" required="">
                  <label class="input__label" for="input-2">
                    <span class="input__label-content">Weight in Kgs</span>
                  </label>
                </span>
        			</div>
              <div class="col-sm-5">
                <span class="input input--focused m-b-md">
                  <input class="input__field cust-col" type="number" name="cons_pkgs" placeholder="Enter No of packages" required="">
                  <label class="input__label" for="input-2">
                    <span class="input__label-content">No of packages</span>
                  </label>
                </span>
              </div>
        		</div><br><br>
        		<div class="form-group">
        			<div class="col-sm-3">
                <span class="input input--focused m-b-md">
                  <input class="input__field cust-col" type="number" name="cons_length" placeholder="Enter length in Metres" required="">
                  <label class="input__label" for="input-2">
                    <span class="input__label-content">Length in Mtrs</span>
                  </label>
                </span>
        			</div>
              <div class="col-sm-3">
                <span class="input input--focused m-b-md">
                  <input class="input__field cust-col" type="number" name="cons_width" placeholder="Enter width in Metres" required="">
                  <label class="input__label" for="input-2">
                    <span class="input__label-content">Width in Mtrs</span>
                  </label>
                </span>
              </div>
              <div class="col-sm-4">
                <span class="input input--focused m-b-md">
                  <input class="input__field cust-col" type="number" name="cons_height" placeholder="Enter height in Metres" required="">
                  <label class="input__label" for="input-2">
                    <span class="input__label-content">Height in Mtrs</span>
                  </label>
                </span>
              </div>
        		</div><br><br>
        		<div class="form-group">
        			<div class="col-sm-3">
                <span class="input input--focused m-b-md">
                  <input class="input__field cust-col" type="number" name="comm_inv" placeholder="Enter commercial invoice number" required="">
                  <label class="input__label" for="input-2">
                    <span class="input__label-content">Commercial invoice number</span>
                  </label>
                </span>
        			</div>
              <div class="col-sm-3">
                <span class="input input--focused m-b-md">
                  <input class="input__field cust-col" type="text" name="comm_inv_date" placeholder="Enter commercial invoice date" required="" data-provide="datepicker">
                  <label class="input__label" for="input-2">
                    <span class="input__label-content">Commercial invoice date</span>
                  </label>
                </span>
              </div>
              <div class="col-sm-4">
                <span class="input input--focused m-b-md">
                  <input class="input__field cust-col" type="text" name="comm_inv_value" placeholder="Enter commercial invoice value" required="" data-provide="datepicker">
                  <label class="input__label" for="input-2">
                    <span class="input__label-content">Commercial invoice value</span>
                  </label>
                </span>
              </div>
        		</div><br><br>
        		<div class="form-group">        			
              <div class="col-sm-5">
                <span class="input input--focused m-b-md">
                  <input class="input__field cust-col" type="text" name="cons_etd" placeholder="Enter consignment ETD" required="" data-provide="datepicker">
                  <label class="input__label" for="input-2">
                    <span class="input__label-content">Consignment ETD</span>
                  </label>
                </span>
              </div>
              <div class="col-sm-5">
                <span class="input input--focused m-b-md">
                  <input class="input__field cust-col" type="text" name="cons_eta" placeholder="Enter consignment ETA" required="" data-provide="datepicker">
                  <label class="input__label" for="input-2">
                    <span class="input__label-content">Consignment ETA</span>
                  </label>
                </span>
              </div>
        		</div><br><br>
            <div class="form-group">              
              <div class="col-sm-5">
                <span class="input input--focused m-b-md">
                  <input class="input__field cust-col" type="text" name="cons_origin_country" placeholder="Enter consignment Origin Country" required="" list="country">
                  <label class="input__label" for="input-2">
                    <span class="input__label-content">Country Origin</span>
                  </label>
                </span>
              </div>
              <div class="col-sm-5">
                <span class="input input--focused m-b-md">
                  <input class="input__field cust-col" type="text" name="cons_destination_country" placeholder="Enter consignment destination Country" required="" list="country">
                  <label class="input__label" for="input-2">
                    <span class="input__label-content">Country destination</span>
                  </label>
                </span>
              </div>
            </div><br><br>
            <div class="form-group">              
              <div class="col-sm-5">
                <span class="input input--focused m-b-md">
                  <input class="input__field cust-col" type="text" name="cons_origin_door" placeholder="Enter consignment door" required="">
                  <label class="input__label" for="input-2">
                    <span class="input__label-content">Origin port</span>
                  </label>
                </span>
              </div>
              <div class="col-sm-5">
                <span class="input input--focused m-b-md">
                  <input class="input__field cust-col" type="text" name="cons_destination_door" placeholder="Enter consignment destination door" required="">
                  <label class="input__label" for="input-2">
                    <span class="input__label-content">Destination port</span>
                  </label>
                </span>
              </div>
            </div><br><br>
            <div class="form-group">              
              <div class="col-sm-10">
                <span class="input input--focused m-b-md">
                  <select class="input__field cust-col" name="cons_category" required="">
                    <option selected="" disabled="">Select category here</option>
                    <option value="1">Door to door</option>
                    <option value="2">Door to port</option>
                  </select>
                  <label class="input__label" for="input-2">
                    <span class="input__label-content">Consignment category</span>
                  </label>
                </span>
              </div>
            </div><br><br>
            <div class="form-group">
              <div class="col-sm-10">
                <button class="btn btn-primary" style="width:100%;">ADD CONSIGNMENT</button>
              </div>
            </div><br><br><br><br><br><br><br><br><br>
          </div>
        	<?php echo form_close();?>
        </div>
      </div>
      <!-- /main area -->
    </div>
    <!-- /content panel -->
    <!-- bottom footer -->
    <!-- Modal -->
<div id="newCompany" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content col-sm-12">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Add new company</h4>
      </div>
      <div class="modal-body">
      <form role="form" method="post" action="<?php echo base_url('sales/addClient');?>" >
        <div class="form-group">
          <input type="text" name="cname" class="form-control" placeholder="Company name">
        </div>
        <div class="form-group">
          <input type="text" name="cemail" class="form-control" placeholder="Company email">
        </div>
        <div class="form-group">
          <input type="text" name="cphone" class="form-control" placeholder="Company Telephone no.">
        </div>
        <div class="form-group">
          <button class="btn btn-primary">Finish</button>
        </div>
      </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>
<!--CLIENT LIST-->
<datalist id="clients">
    <?php foreach ($clients as $clients):?>
        <option value="<?php echo $clients->cust_id;?>"><?php echo $clients->client_name;?></option>
    <?php endforeach;?>
</datalist>
<datalist id="shipper">
    <option value="Avmax">Avmax</option>
</datalist>
<!--CSS-->
<style type="text/css">
  .cust-col{
    border-right: none; 
    border-top: none;
    border-left: none; 
    border-bottom-color: #b3b3ff; 
  }
  .c30{
    width: 100%;
  }
</style>
<script type="text/javascript">
  jQuery(function($){
  $('.table').footable({
    "showToggle": true
  });
});
